function quali()
    mainInterface = startMainInterface();
end

function mainFig = startMainInterface()
    % Make program full screen
    screenSize = get(0, 'ScreenSize');
    
    mainFig = figure('Position', screenSize,...
        'MenuBar', 'none',...
        'NumberTitle', 'off',...
        'Name', ['Qualitative Analysis of Lung Images - 0.0.0dev0 -'...
                 ' Matlab Version'],...
        'Color', [0.15, 0.15, 0.15]);
    
    % Upper Panel with all options
    mainPanel = uipanel('Parent', mainFig,...
        'Units', 'Normalized',...
        'Position', [0.005, 0.87, 0.99, 0.12],...
        'Title', '',...
        'BackGroundColor', [0.2, 0.2, 0.2]);
    
    uicontrol('Parent', mainPanel,...
        'Units', 'Normalized',...
        'Position', [0.01, 0.2, 0.08, 0.6],...
        'String', 'Import Dicom',...
        'BackGroundColor', [0.15, 0.15, 0.15],...
        'ForeGroundColor', [54/255, 189/255, 1],...
        'FontWeight', 'Bold',...
        'FontSize', 14);
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                             CALLBACKS                                
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%