function quali()
    mainInterface = startMainInterface();
end

function mainFig = startMainInterface()
    % Make program full screen
    screenSize = get(0, 'ScreenSize');
    mainInterfaceColor = [0, 0, 0];
    
   mainFig = figure('Position', screenSize,...
        'MenuBar', 'none',...
        'NumberTitle', 'off',...
        'Name', ['Qualitative Analysis of Lung Images - 0.0.0dev0 -'...
                 ' Matlab Version'],...
        'Color', mainInterfaceColor,...
        'Resize', 'On',...
        'WindowButtonMotionFcn', @mouseMove,...
        'WindowScrollWheelFcn', @refreshSlicePosition);
    
   sidePanel = uipanel('Parent', mainFig,...
       'Units', 'Normalized',...
       'Position', [0, 0, 0.25, 1],...
       'Backgroundcolor', [0.1, 0.1, 0.1]);
   
   imageOptionsPanel = uipanel('Parent', sidePanel,...
       'Units', 'Normalized',...
       'Position', [0, 0.45, 1, 0.55],...
       'FontSize',14,...
       'FontWeight','Bold',...
       'Backgroundcolor', [0.1, 0.1, 0.1],...
       'Foregroundcolor', [1, 1, 1],...
       'Title', 'Image Options');
         
   createImageOptionsWidgets(imageOptionsPanel, [0.1, 0.1, 0.1]);   
   
   metadataPanel = uipanel('Parent', sidePanel,...
       'Units', 'Normalized',...
       'Position', [0, 0.0, 1, 0.45],...
       'FontSize',14,...
       'FontWeight','Bold',...
       'Backgroundcolor', [0.1, 0.1, 0.1],...
       'Foregroundcolor', [1, 1, 1],...
       'Title', 'Metadata');
   
   startAxesMetadataInfo(metadataPanel, [0.1, 0.1, 0.1]);
   
   uicontrol('Parent', mainFig,...
       'Units', 'Normalized',...
       'Position', [0.6, 0.005, 0.06, 0.03],...
       'Style', 'Text',...
       'Foregroundcolor', [1, 1, 1],...
       'Backgroundcolor', mainInterfaceColor,...
       'Fontsize', 13,...
       'Horizontalalignment', 'Center',...
       'String', '',...
       'Tag', 'textSliceNumber');
   
   uicontrol('Parent', mainFig,...
       'Style', 'Text',...
       'Units', 'Normalized',...
       'Position', [0.255, 0.005, 0.15, 0.03],...
       'BackgroundColor', mainInterfaceColor,...
       'Foregroundcolor', [1, 1, 1]',...
       'HorizontalAlignment', 'Left',...
       'FontSize', 14,...
       'String', '',...
       'Tag', 'textPixelValue');
    
    uicontrol('Parent', mainFig,...
        'Style', 'Text',...
        'Units', 'Normalized',...
        'Position', [0.87, 0.005, 0.2, 0.03],...
        'BackgroundColor', mainInterfaceColor,...
        'Foregroundcolor', [1, 1, 1]',...
        'HorizontalAlignment', 'Left',...
        'FontSize', 14,...
        'String', '',...
        'Tag', 'textSliceLocation');
   
   uicontrol('Parent', mainFig,...
       'Units', 'Normalized',...
       'Position', [0.255, 0.96, 0.12, 0.03],...
       'Style', 'Text',...
       'Foregroundcolor', [1, 1, 1],...
       'Backgroundcolor', mainInterfaceColor,...
       'Fontsize', 13,...
       'HorizontalAlignment', 'Left',...
       'String', '', ...
       'Tag', 'textWindowWL')
   
   
   statusPanel = uipanel('Parent', sidePanel,...
       'Units', 'Normalized',...
       'Position', [0, 0.0, 1, 0.04],...
       'FontSize',14,...
       'FontWeight','Bold',...
       'Backgroundcolor', [0.1, 0.1, 0.1],...
       'Foregroundcolor', [1, 1, 1]');
   
   uicontrol('Parent', statusPanel,...
       'Units', 'Normalized',...
       'Position', [0.05, 0.05, 0.9, 0.8],...
       'Style', 'Text',...
       'Foregroundcolor', [1, 1, 1],...
       'Backgroundcolor', [0.1, 0.1, 0.1],...
       'Fontsize', 13,...
       'Horizontalalignment', 'Center',...
       'String', 'Ready!',...
       'Tag', 'statusText');
    
      uicontrol('Parent', statusPanel,...
       'Units', 'Normalized',...
       'Position', [0.05, 0.4, 0.05, 0.2],...
       'Style', 'Text',...
       'Fontsize', 13,...
       'Backgroundcolor', 'g',...
       'String', '',...
       'Tag', 'statusLight');
   
%   informationAxes = axes('Parent', mainFig,...
%       'Units', 'Normalized',...
%       'Position', [0, 0.06, 1, 0.85],...
%       'Color', [0, 0, 0],...
%       'XTickLabel', [],...
%       'YTickLabel', [],...
%       'Xcolor', [0, 0, 0],...
%       'Ycolor', [0, 0, 0],...
%       'Tag', 'informationAxes');
  
  imageAxes = axes('Parent', mainFig,...
        'Units', 'Normalized',...
        'Position', [0.2750    0.1300    0.700    0.7800],...
        'Color', [0, 0, 0],...
        'XTickLabel', [],...
        'YTickLabel', [],...
        'Xcolor', [0, 0, 0],...
        'Ycolor', [0, 0, 0],...
        'Tag', 'imageAxes');
    
    mainMenu = uimenu('parent', mainFig,...
        'Label', 'File');
    importMenu = uimenu('Parent', mainMenu,...
        'Label', 'Import');
    
    uimenu('Parent', importMenu,...
        'Label', 'Dicom',...
        'Callback', @openImage);
    
    uimenu('Parent', importMenu,...
        'Label', 'Mat File',...
        'Tag', 'importMaskButton',...
        'Callback', @openMatFile);
    
    uimenu('Parent', importMenu,...
        'Label', 'Mask',...
        'Tag', 'importMaskButton',...
        'Callback', @openMask);

    uicontrol('Parent', mainFig,...
        'Style', 'slider',...
        'Units', 'Normalized',...
        'Visible', 'Off',...
        'Backgroundcolor', [0, 0, 0],...
        'Min',1,...
        'Max',1,...
        'Value', 1,...
        'Position', [0.38    0.01    0.50    0.10],...
        'Callback', @moveSlider,...
        'Tag', 'slider');
    
     
    %Start data handles
    handles.data = '';
    
    handles.gui = guihandles(mainFig);
    guidata(mainFig, handles);
end

function createImageOptionsWidgets(imageOptionsPanel, bckColor)    

    % Window Width
    uicontrol('Parent', imageOptionsPanel,...
        'Units', 'Normalized',...
        'Position', [0.05, 0.9, 0.35, 0.05],...
        'Style', 'Text',...
        'String', 'Window Width:',...
        'Fontsize', 14,....
        'Fontweight', 'bold',...
        'Horizontalalignment', 'Left',...
        'BackGroundColor', bckColor,...
        'ForeGroundColor', [1, 1, 1])
    
     uicontrol('Parent', imageOptionsPanel,...
        'Units', 'Normalized',...
        'Position', [0.42, 0.885, 0.35, 0.05],...
        'Style', 'Slider',...
        'Min', -1500,...
        'Max', 1490,...
        'BackGroundColor', bckColor,...
        'ForeGroundColor', [1, 1, 1],...
        'Tag', 'sliderWindowWidth',...
        'Callback', @updateWindowLevelCallback)
    
     uicontrol('Parent', imageOptionsPanel,...
        'Units', 'Normalized',...
        'Position', [0.8, 0.89, 0.15, 0.05],...
        'Style', 'Edit',...
        'String', '',...
        'Fontsize', 14,....
        'Fontweight', 'bold',...
        'Horizontalalignment', 'Center',...
        'BackGroundColor', [0.2, 0.2, 0.2],...
        'ForeGroundColor', [1, 1, 1],...
        'Tag', 'editWindowWidth',...
        'Callback', @updateWindowLevelEdit)
    
     % Window Max
     uicontrol('Parent', imageOptionsPanel,...
        'Units', 'Normalized',...
        'Position', [0.05, 0.83, 0.37, 0.05],...
        'Style', 'Text',...
        'String', 'Window Level:',...
        'Fontsize', 14,....
        'Fontweight', 'bold',...
        'Horizontalalignment', 'Left',...
        'BackGroundColor', bckColor,...
        'ForeGroundColor', [1, 1, 1])
    
     uicontrol('Parent', imageOptionsPanel,...
        'Units', 'Normalized',...
        'Position', [0.42, 0.82, 0.35, 0.05],...
        'Style', 'Slider',...
         'Min', -1490,...
        'Max', 1500,...1
        'BackGroundColor', bckColor,...
        'ForeGroundColor', [1, 1, 1],...
        'Tag', 'sliderWindowLevel',...
        'Callback', @updateWindowLevelCallback)
    
     uicontrol('Parent', imageOptionsPanel,...
        'Units', 'Normalized',...
        'Position', [0.8, 0.83, 0.15, 0.05],...
        'Style', 'Edit',...
        'String', '',...
        'Fontsize', 14,....
        'Fontweight', 'bold',...
        'Horizontalalignment', 'Center',...
        'BackGroundColor', [0.2, 0.2, 0.2],...
        'ForeGroundColor', [1, 1, 1],...
        'Tag', 'editWindowLevel',...
        'Callback', @updateWindowLevelEdit);
    
    uicontrol('Parent', imageOptionsPanel,...
        'Units', 'Normalized',...
        'Position', [0.15, 0.64, 0.5, 0.1],...
        'Style', 'Popupmenu',...
        'String', {'Lung', 'Bone', 'Mediastinum', 'Soft tissues'},...
        'Fontsize', 14,....
        'Tag', 'popWindowWidthLevel',...
        'Fontweight', 'bold');
    
    uicontrol('Parent',imageOptionsPanel,...
        'Units', 'Normalized',...
        'Position', [0.65, 0.66, 0.2, 0.1],...
        'String', 'Set',...
        'Fontsize', 14,....
        'Fontweight', 'bold',...
        'Callback', @setWindowWidthLevelButton);
    
    % Flip Image
     uicontrol('Parent', imageOptionsPanel,...
        'Units', 'Normalized',...
        'Position', [0.1, 0.56, 0.35, 0.05],...
        'Style', 'Text',...
        'String', 'Flip Image:',...
        'Fontsize', 14,....
        'Fontweight', 'bold',...
        'Horizontalalignment', 'Left',...
        'BackGroundColor', bckColor,...
        'ForeGroundColor', [1, 1, 1])
    
    uicontrol('Parent', imageOptionsPanel,...
        'Units', 'Normalized',...
        'Position', [0.35, 0.56, 0.25, 0.05],...
        'Style', 'Popupmenu',...
        'String', {'z', 'x', 'y'},...
        'Fontsize', 14,....
        'Fontweight', 'bold',...
        'Tag', 'popFlipImage')
    
    uicontrol('Parent', imageOptionsPanel,...
        'Units', 'Normalized',...
        'Position', [0.6, 0.545, 0.25, 0.06],...
        'Style', 'Pushbutton',...
        'String', 'Flip',...
        'Fontsize', 14,....
        'Fontweight', 'bold',...
        'Tag', 'buttonFlipImage',...
        'Enable', 'Off',...
        'Callback', {@flipImageOrMask, 'image'}) 
    
    % Flip Mask
    uicontrol('Parent', imageOptionsPanel,...
        'Units', 'Normalized',...
        'Position', [0.1, 0.46, 0.35, 0.05],...
        'Style', 'Text',...
        'String', 'Flip Mask:',...
        'Fontsize', 14,....
        'Fontweight', 'bold',...
        'Horizontalalignment', 'Left',...
        'BackGroundColor', bckColor,...
        'ForeGroundColor', [1, 1, 1])
    
    uicontrol('Parent', imageOptionsPanel,...
        'Units', 'Normalized',...
        'Position', [0.35, 0.46, 0.25, 0.05],...
        'Style', 'Popupmenu',...
        'String', {'z', 'x', 'y'},...
        'Fontsize', 14,....
        'Fontweight', 'bold',...
        'Tag', 'popFlipMask')
    
    uicontrol('Parent', imageOptionsPanel,...
        'Units', 'Normalized',...
        'Position', [0.6, 0.4455, 0.25, 0.06],...
        'Style', 'Pushbutton',...
        'String', 'Flip',...
        'Fontsize', 14,....
        'Fontweight', 'bold',...
        'Tag', 'buttonFlipMask',...
        'Enable', 'Off',...
        'Callback', {@flipImageOrMask, 'mask'})  
    
    uicontrol('Parent', imageOptionsPanel,...
        'Units', 'Normalized',...
        'Position', [0.05, 0.3, 0.26, 0.05],...
        'Style', 'Text',...
        'String', 'Orientation:',...
        'Horizontalalignment', 'Left',...
        'Fontsize', 14,....
        'Backgroundcolor', bckColor,...
        'Foregroundcolor', [1, 1, 1],...
        'Fontweight', 'bold')
    
    orientationGroup = uibuttongroup('Parent', imageOptionsPanel,...
        'Units', 'Normalized',...
        'Position', [0.32, 0.24, 0.5, 0.15],...
        'Bordertype', 'None',...
        'Backgroundcolor', bckColor,...
        'Tag', 'orientationGroup');
    
    uicontrol('Parent', orientationGroup,...
        'Units', 'Normalized',...
        'Position', [0.05, 0.7, 0.9, 0.3],...
        'Style', 'Radio',...
        'String', 'Transversal',...
        'Fontsize', 14,...
        'Backgroundcolor', bckColor,...
        'Foregroundcolor', [1, 1, 1],...
        'Value', 1,...
        'Tag', 'transversalOption',...
        'Callback', @changeOrientation);
    
    uicontrol('Parent', orientationGroup,...
        'Units', 'Normalized',...
        'Position', [0.05, 0.35, 0.9, 0.3],...
        'Style', 'Radio',...
        'String', 'Sagittal',...
        'Fontsize', 14,...
        'Backgroundcolor', bckColor,...
        'Foregroundcolor', [1, 1, 1],...
        'Value', 0,...
        'Tag', 'sagittalOption',...
        'Callback', @changeOrientation);
       
     uicontrol('Parent', orientationGroup,...
        'Units', 'Normalized',...
        'Position', [0.05, 0.0, 0.9, 0.3],...
        'Style', 'Radio',...
        'String', 'Coronal',...
        'Fontsize', 14,...
        'Backgroundcolor', bckColor,...
        'Foregroundcolor', [1, 1, 1],...
        'Value', 0,...
        'Tag', 'coronalOption',...
        'Callback', @changeOrientation);
         
     uicontrol('Parent', imageOptionsPanel,...
        'Units', 'Normalized',...
        'Position', [0.05, 0.12, 0.35, 0.05],...
        'Style', 'Text',...
        'String', 'Mask Settings:',...
        'Fontsize', 14,....
        'Fontweight', 'bold',...
        'Horizontalalignment', 'Left',...
        'BackGroundColor', bckColor,...
        'ForeGroundColor', [1, 1, 1])
    
     uicontrol('Parent', imageOptionsPanel,...
        'Units', 'Normalized',...
        'Position', [0.41, 0.106, 0.07, 0.06],...
        'Style', 'Pushbutton',...
        'String', '',...
        'Fontsize', 14,....
        'Fontweight', 'bold',...
        'Horizontalalignment', 'Left',...
        'BackGroundColor', bckColor,...
        'ForeGroundColor', [1, 1, 1],...
        'Enable', 'Off',...
        'Callback', @maskSettings,...
        'Tag', 'buttonMaskSettings')
        
    uicontrol('Parent', imageOptionsPanel,...
        'Units', 'Normalized',...
        'Position', [0.038, 0.03, 0.55, 0.05],...
        'Style', 'Check',...
        'String', 'Show Mask Overlay',...
        'Fontsize', 14,....
        'Fontweight', 'bold',...
        'BackGroundColor', bckColor,...
        'ForeGroundColor', [1, 1, 1],...
        'Tag', 'showMaskCheck',...
        'Enable', 'Off',...
        'Callback', @showMask)
        
end


function startAxesMetadataInfo(metadataPanel, bckColor)
    uicontrol('Parent', metadataPanel,...
        'Style', 'Text',...
        'Units', 'Normalized',...
        'Position', [0.05, 0.9, 0.35, 0.1],...        
        'BackgroundColor', bckColor,...
        'Foregroundcolor', [1, 1, 1]',...
        'HorizontalAlignment', 'Left',...
        'FontSize', 14,...
        'Fontweight', 'Bold',...
        'String', 'Patient Name:');
    
     uicontrol('Parent', metadataPanel,...
        'Style', 'Text',...
        'Units', 'Normalized',...
        'Position', [0.37, 0.9, 0.85, 0.1],...        
        'BackgroundColor', bckColor,...
        'Foregroundcolor', [1, 1, 1]',...
        'HorizontalAlignment', 'Left',...
        'FontSize', 14,...
        'String', '',...
        'Tag', 'textPatientName');
    
    uicontrol('Parent', metadataPanel,...
        'Style', 'Text',...
        'Units', 'Normalized',...
        'Position', [0.05, 0.82, 0.12, 0.1],...        
        'BackgroundColor', bckColor,...
        'Foregroundcolor', [1, 1, 1]',...
        'HorizontalAlignment', 'Left',...
        'FontSize', 14,...
        'Fontweight', 'Bold',...
        'String', 'Age:');
    
     uicontrol('Parent', metadataPanel,...
        'Style', 'Text',...
        'Units', 'Normalized',...
        'Position', [0.19, 0.82, 0.20, 0.1],...        
        'BackgroundColor', bckColor,...
        'Foregroundcolor', [1, 1, 1]',...
        'HorizontalAlignment', 'Left',...
        'FontSize', 14,...
        'String', '',...
        'Tag', 'textAge');
 
    
        uicontrol('Parent', metadataPanel,...
        'Style', 'Text',...
        'Units', 'Normalized',...
        'Position', [0.05, 0.74, 0.35, 0.1],...        
        'BackgroundColor', bckColor,...
        'Foregroundcolor', [1, 1, 1]',...
        'HorizontalAlignment', 'Left',...
        'FontSize', 14,...
        'Fontweight', 'Bold',...
        'String', 'Study Descr:');
    
     uicontrol('Parent', metadataPanel,...
        'Style', 'Text',...
        'Units', 'Normalized',...
        'Position', [0.34, 0.74, 0.85, 0.1],...        
        'BackgroundColor', bckColor,...
        'Foregroundcolor', [1, 1, 1]',...
        'HorizontalAlignment', 'Left',...
        'FontSize', 14,...
        'String', '',...
        'Tag', 'textStudyDescription');
    
    uicontrol('Parent', metadataPanel,...
        'Style', 'Text',...
        'Units', 'Normalized',...
        'Position', [0.05, 0.66, 0.35, 0.1],...
        'BackgroundColor', bckColor,...
        'Foregroundcolor', [1, 1, 1]',...
        'HorizontalAlignment', 'Left',...
        'FontSize', 14,...
        'Fontweight', 'Bold',...
        'String', 'Series Descr:');
    
     uicontrol('Parent', metadataPanel,...
        'Style', 'Text',...
        'Units', 'Normalized',...
        'Position', [0.35, 0.66, 0.85, 0.1],...        
        'BackgroundColor', bckColor,...
        'Foregroundcolor', [1, 1, 1]',...
        'HorizontalAlignment', 'Left',...
        'FontSize', 14,...
        'String', '',...
        'Tag', 'textSeriesDescription');
 
    
    uicontrol('Parent', metadataPanel,...
        'Style', 'Text',...
        'Units', 'Normalized',...
        'Position', [0.05, 0.58, 0.35, 0.1],...
        'BackgroundColor', bckColor,...
        'Foregroundcolor', [1, 1, 1]',...
        'HorizontalAlignment', 'Left',...
        'FontSize', 14,...
        'Fontweight', 'Bold',...
        'String', 'Study Data:');
    
     uicontrol('Parent', metadataPanel,...
        'Style', 'Text',...
        'Units', 'Normalized',...
        'Position', [0.32, 0.58, 0.85, 0.1],...        
        'BackgroundColor', bckColor,...
        'Foregroundcolor', [1, 1, 1]',...
        'HorizontalAlignment', 'Left',...
        'FontSize', 14,...
        'String', '',...
        'Tag', 'textStudyDate');
    
    
     uicontrol('Parent', metadataPanel,...
        'Style', 'Text',...
        'Units', 'Normalized',...
        'Position', [0.05, 0.48, 0.37, 0.1],...        
        'BackgroundColor', bckColor,...
        'Foregroundcolor', [1, 1, 1]',...
        'HorizontalAlignment', 'Left',...
        'FontSize', 14,...
        'Fontweight', 'Bold',...
        'String', 'Slice Thickness:');
    
     uicontrol('Parent', metadataPanel,...
        'Style', 'Text',...
        'Units', 'Normalized',...
        'Position', [0.41, 0.48, 0.85, 0.1],...        
        'BackgroundColor', bckColor,...
        'Foregroundcolor', [1, 1, 1]',...
        'HorizontalAlignment', 'Left',...
        'FontSize', 14,...
        'String', '',...
        'Tag', 'textSliceThickness');
    
    
     uicontrol('Parent', metadataPanel,...
        'Style', 'Text',...
        'Units', 'Normalized',...
        'Position', [0.05, 0.40, 0.4, 0.1],...        
        'BackgroundColor', bckColor,...
        'Foregroundcolor', [1, 1, 1]',...
        'HorizontalAlignment', 'Left',...
        'FontSize', 14,...
        'Fontweight', 'Bold',...
        'String', 'Space Btw Slices:');
    
     uicontrol('Parent', metadataPanel,...
        'Style', 'Text',...
        'Units', 'Normalized',...
        'Position', [0.44, 0.40, 0.85, 0.1],...        
        'BackgroundColor', bckColor,...
        'Foregroundcolor', [1, 1, 1]',...
        'HorizontalAlignment', 'Left',...
        'FontSize', 14,...
        'String', '',...
        'Tag', 'textSpacingBetweenSlices');
    
     uicontrol('Parent', metadataPanel,...
        'Style', 'Text',...
        'Units', 'Normalized',...
        'Position', [0.05, 0.32, 0.5, 0.1],...        
        'BackgroundColor', bckColor,...
        'Foregroundcolor', [1, 1, 1]',...
        'HorizontalAlignment', 'Left',...
        'FontSize', 14,...
        'Fontweight', 'Bold',...
        'String', 'Image Dimensions:');
    
     uicontrol('Parent', metadataPanel,...
        'Style', 'Text',...
        'Units', 'Normalized',...
        'Position', [0.48, 0.32, 0.85, 0.1],...        
        'BackgroundColor', bckColor,...
        'Foregroundcolor', [1, 1, 1]',...
        'HorizontalAlignment', 'Left',...
        'FontSize', 14,...
        'String', '',...
        'Tag', 'textImageDimensions');  
    
     uicontrol('Parent', metadataPanel,...
        'Style', 'Text',...
        'Units', 'Normalized',...
        'Position', [0.05, 0.06, 0.5, 0.1],...
        'BackgroundColor', bckColor,...
        'Foregroundcolor', [1, 1, 1]',...
        'HorizontalAlignment', 'Left',...
        'FontSize', 14,...
        'Fontweight', 'Bold',...
        'String', 'Voxel Volume:');
    
    uicontrol('Parent', metadataPanel,...
        'Style', 'Text',...
        'Units', 'Normalized',...
        'Position', [0.38, 0.06, 0.85, 0.1],...
        'BackgroundColor', bckColor,...
        'Foregroundcolor', [1, 1, 1]',...
        'HorizontalAlignment', 'Left',...
        'FontSize', 14,...
        'String', '',...
        'Tag', 'textVoxelVolume');
    

 end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                             CALLBACKS                                
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function maskSettings(hObject, eventdata)
    handles = guidata(hObject);
    % Create custom color palette
    
    currentRgb = handles.data.imageCoreInfo.maskSettings.rgb;
    currentOpacity = handles.data.imageCoreInfo.maskSettings.opacity;
    
    fig = figure('Position', [0, 0, 300, 400],...
        'MenuBar', 'none',...
        'NumberTitle', 'off',...
        'Name', 'Mask Settings',...
        'Color', [0, 0, 0],...
        'Resize', 'Off',...
        'Visible', 'Off',...
        'Tag', 'fig');    
    movegui(fig, 'center')
    set(fig, 'Visible', 'On')
    
    % Main color palette panel
    mainPanel = uipanel('Parent', fig,...
        'Units', 'Normalized',...
        'Position', [0, 0.3, 1, 0.7],...
        'Backgroundcolor', [0.1, 0.1, 0.1],...
        'Title', 'Colors',...
        'Foregroundcolor', [1, 1, 1],...
        'Fontsize', 14,...
        'Fontweight', 'Bold');
    
    % Color axes
    positions = {[0.1, 0.9, 0.1, 0.1], [0.22, 0.9, 0.1, 0.1],...
                 [0.34, 0.9, 0.1, 0.1], [0.46, 0.9, 0.1, 0.1],...
                 [0.1, 0.75, 0.1, 0.1], [0.22, 0.75, 0.1, 0.1],...
                 [0.34, 0.75, 0.1, 0.1], [0.46, 0.75, 0.1, 0.1]};
    colors = {[0, 1, 0], [0, 0.45, 0.74], [0.85, 0.33, 0.1],...
              [0.64, 0.08, 0.18],  [1, 1, 0],...
              [0, 1, 1], [0.93, 0.69, 0.13],...
              [0.94, 0.94, 0.94], [0.94, 0.94, 0.94]};
    for i = 1:8
        axes('Parent', mainPanel,...
             'Units', 'Normalized',...
             'Position', positions{i},...
             'XTickLabel', [],...
             'YTickLabel', [],...
             'Xcolor', [0, 0, 0],...
             'Ycolor', [0, 0, 0],...
             'Color', colors{i},...
             'ButtonDownFcn', @changeColor)
    end
        
    % Preview
    uicontrol('Parent', mainPanel,...
        'Units', 'Normalized',...
        'Position', [0.72, 0.71, 0.2, 0.07],...
        'Style', 'Text',...
        'String', 'Preview',...
        'Fontweight', 'Bold',...
        'Fontsize', 14,...
        'Backgroundcolor', [0.1, 0.1, 0.1],...
        'Foregroundcolor', [1, 1, 1]);
    
    axes('Parent', mainPanel,...
        'Units', 'Normalized',...
        'Position', [0.7, 0.45, 0.25, 0.25],...
        'Color', currentRgb,...
        'Tag', 'previewAxes');
    
    uicontrol('Parent', mainPanel,...
        'Units', 'Normalized',...
        'Position', [0.31, 0.15, 0.1, 0.1],...
        'Style', 'Text',...
        'String', 'R',...
        'Fontweight', 'Bold',...
        'Fontsize', 14,...
        'Backgroundcolor', [0.1, 0.1, 0.1],...
        'Foregroundcolor', [1, 1, 1]);
    uicontrol('Parent', mainPanel,...
        'Units', 'Normalized',...
        'Position', [0.3, 0.05, 0.12, 0.1],...
        'Style', 'Edit',...
        'String', num2str(currentRgb(1)),...
        'Tag', 'rEdit');
    
    uicontrol('Parent', mainPanel,...
        'Units', 'Normalized',...
        'Position', [0.46, 0.15, 0.1, 0.1],...
        'Style', 'Text',...
        'String', 'G',...
        'Fontweight', 'Bold',...
        'Fontsize', 14,...
        'Backgroundcolor', [0.1, 0.1, 0.1],...
        'Foregroundcolor', [1, 1, 1]);
    uicontrol('Parent', mainPanel,...
        'Units', 'Normalized',...
        'Position', [0.45, 0.05, 0.12, 0.1],...
        'Style', 'Edit',...
        'String', num2str(currentRgb(2)),...
        'Tag', 'gEdit');    
    
    uicontrol('Parent', mainPanel,...
        'Units', 'Normalized',...
        'Position', [0.61, 0.15, 0.1, 0.1],...
        'Style', 'Text',...
        'String', 'B',...
        'Fontweight', 'Bold',...
        'Fontsize', 14,...
        'Backgroundcolor', [0.1, 0.1, 0.1],...
        'Foregroundcolor', [1, 1, 1]);
    uicontrol('Parent', mainPanel,...
        'Units', 'Normalized',...
        'Position', [0.6, 0.05, 0.12, 0.1],...
        'Style', 'Edit',...
        'String', num2str(currentRgb(3)),...
        'Tag', 'bEdit');
    
    % Opacity
    uicontrol('Parent', fig,...
        'Units', 'Normalized',...
        'Position', [0.25, 0.19, 0.3, 0.1],...
        'Style', 'Text',...
        'String', 'Opacity',...
        'Fontweight', 'Bold',...
        'Fontsize', 14,...
        'Backgroundcolor', [0, 0, 0],...
        'Foregroundcolor', [1, 1, 1]);
    uicontrol('Parent', fig,...
        'Units', 'Normalized',...
        'Position', [0.1, 0.13, 0.6, 0.1],...
        'Style', 'Slider',...
        'Min', 0,...
        'Max', 1,...
        'Value', currentOpacity,...
        'BackGroundColor', [0, 0, 0],...
        'ForeGroundColor', [1, 1, 1],...
        'Callback', @opacityCallback,...
        'Tag', 'opacitySlider')
    
    uicontrol('Parent', fig,...
        'Units', 'Normalized',...
        'Position', [0.72, 0.18, 0.1, 0.07],...
        'Style', 'Edit',...
        'String', num2str(currentOpacity),...
        'Fontweight', 'Bold',...
        'Tag', 'opacityEdit')
        
    uicontrol('Parent', fig,...
        'String', 'Ok',...
        'Units', 'Normalized',...
        'Position', [0.5, 0.0, 0.25, 0.1],...
        'Fontweight', 'bold',...
        'Fontsize', 14,...
        'Callback', @okMaskSettings);
    uicontrol('Parent', fig,...
        'String', 'Cancel',...
        'Units', 'Normalized',...
        'Position', [0.74, 0.0, 0.25, 0.1],...
        'Fontweight', 'bold',...
        'Fontsize', 14,...
        'Callback', @cancelMaskSettings);
    
    handles.mask_settings = guihandles(fig);
    guidata(fig, handles);
    
    function opacityCallback(hObject, eventdata)
        handles = guidata(hObject);
        value = get(handles.mask_settings.opacitySlider, 'Value');
        set(handles.mask_settings.opacityEdit, 'String', value);
    end

    function changeColor(hObject, eventdata)
        handles = guidata(hObject);
        currentColor = get(eventdata.Source, 'Color');
        set(handles.mask_settings.previewAxes, 'Color', currentColor);
        
        set(handles.mask_settings.rEdit, 'String', currentColor(1))
        set(handles.mask_settings.gEdit, 'String', currentColor(2))
        set(handles.mask_settings.bEdit, 'String', currentColor(3))
    end

    function okMaskSettings(hObject, eventdata)
        handles = guidata(hObject);        
        [r, g, b, op] = getSettings(handles.mask_settings);        
        
        handles.data.imageCoreInfo.maskSettings.rgb = [r, g, b];
        handles.data.imageCoreInfo.maskSettings.opacity = op;
        
        uiresume(handles.mask_settings.fig);
        handles = rmfield(handles, 'mask_settings');        
        delete(fig);
    end

    function [r, g, b, op] = getSettings(maskHandles)
        r = str2double(get(maskHandles.rEdit, 'String'));
        g = str2double(get(maskHandles.gEdit, 'String'));
        b = str2double(get(maskHandles.bEdit, 'String'));
        op = get(maskHandles.opacitySlider, 'Value');
    end

    function cancelMaskSettings(hObject, eventdata)
        handles = guidata(hObject);   
        uiresume(handles.mask_settings.fig)
        handles = rmfield(handles, 'mask_settings');        
        delete(fig);
    end
    uiwait(fig)   
    
    guidata(hObject, handles);
    
    % Refresh mask view
    maskOverlayWrapper(handles)
end

function setWindowWidthLevelButton(hObject, eventdata)
    handles = guidata(hObject);
    options = get(handles.gui.popWindowWidthLevel, 'String');
    
    selectedOption = options{get(handles.gui.popWindowWidthLevel, 'Value')};
    
    switch selectedOption
        case 'Lung'
            refreshWindowWidthLevel(handles, 1500, -600)
        case 'Bone'
            refreshWindowWidthLevel(handles, 1800, 400)
        case 'Mediastinum'
            refreshWindowWidthLevel(handles, 350, 50)
        case 'Soft tissues'
            refreshWindowWidthLevel(handles, 400, 50)
    end
end

function updateWindowLevelEdit(hObject, eventdata)
    handles = guidata(hObject);
    windowWidth = str2double(get(handles.gui.editWindowWidth, 'String'));
    windowLevel = str2double(get(handles.gui.editWindowLevel, 'String'));
    
    refreshWindowWidthLevel(handles, windowWidth, windowLevel)
end

function updateWindowLevelCallback(hObject, eventdata)
    handles = guidata(hObject);
    windowWidth = get(handles.gui.sliderWindowWidth, 'Value');
    windowLevel = get(handles.gui.sliderWindowLevel, 'Value');
    
    refreshWindowWidthLevel(handles, windowWidth, windowLevel)
end

function changeOrientation(hObject, eventdata)
    handles = guidata(hObject);
    
    orientation = getOrientationName(...,
        handles.gui.transversalOption,...
        handles.gui.sagittalOption);

    switch orientation
        case 'transversal'
            [handles, currentPosition, nSlices] = rotateTransversal(handles);
        case 'sagittal'
            [handles, currentPosition, nSlices] = rotateSagittal(handles);
        otherwise 
            [handles, currentPosition, nSlices] = rotateCoronal(handles);
    end
    
   handles.data.orientation = orientation; 
   handles.data.imageCoreInfo.nSlices = nSlices;
    
  updateSliceNumberText(handles.gui.textSliceNumber,...
        currentPosition, nSlices)
    
   firstPosition = startSlider(handles.gui.slider,...
        handles.data.imageCoreInfo.nSlices);
    
   aspect = calculateDAspect(handles.gui.transversalOption,...
        handles.gui.sagittalOption, handles.data.imageCoreInfo.metadata{1},...
        handles.data.imageCoreInfo.metadata{2});
    
   imageSlice = squeeze(handles.data.imageCoreInfo.matrix(:, :,...
        currentPosition, :));
        
    showImageSlice(handles.gui.imageAxes,...
        imageSlice, handles.data.Rmin, handles.data.Rmax,...
        aspect);
    
    if get(handles.gui.showMaskCheck, 'Value')
        createMaskOverlay(handles,...
            handles.data.imageCoreInfo.masks(:, :, currentPosition),...
            aspect)
    end
    
    guidata(hObject, handles)
end

function [handles, currentPosition, nSlices] = rotateTransversal(handles)
    handles.data.imageCoreInfo.matrix = handles.data.imageCoreInfo.matrixTransversal;
    nSlices = handles.data.imageCoreInfo.sizeTransversal;
    currentPosition = round(nSlices / 2);
    
    % Change mask orientation
    if isfield(handles.data.imageCoreInfo, 'masks')
        handles.data.imageCoreInfo.masks = handles.data.imageCoreInfo.masksTransversal;
    end
end


function [handles, currentPosition, nSlices] = rotateSagittal(handles)
    handles.data.imageCoreInfo.matrix = handles.data.imageCoreInfo.matrixSagittal;
    nSlices = handles.data.imageCoreInfo.sizeSagittal;
    currentPosition = round(nSlices / 2);
    
    % Change mask orientation
    if isfield(handles.data.imageCoreInfo, 'masks')
        handles.data.imageCoreInfo.masks = handles.data.imageCoreInfo.masksSagittal;
    end
end

function [handles, currentPosition, nSlices] = rotateCoronal(handles)
    handles.data.imageCoreInfo.matrix = handles.data.imageCoreInfo.matrixCoronal;
    nSlices = handles.data.imageCoreInfo.sizeCoronal;
    currentPosition = round(nSlices/ 2);
    
        % Change mask orientation
    if isfield(handles.data.imageCoreInfo, 'masks')
        handles.data.imageCoreInfo.masks = handles.data.imageCoreInfo.masksCoronal;
    end
end

function startWindowWidthLevelSliders(handles, img, Win, LevV)

    set(handles.gui.sliderWindowWidth, 'Min', min(img(:)))
    set(handles.gui.sliderWindowWidth, 'Max', max(img(:)))
    
    set(handles.gui.sliderWindowLevel, 'Min', min(img(:)))
    set(handles.gui.sliderWindowLevel, 'Max', max(img(:)))
    
    windowMin = Win / 2  - LevV;
    windowMax = Win / 2 + LevV;
    
    set(handles.gui.sliderWindowWidth, 'Value', windowMin);
    set(handles.gui.sliderWindowLevel, 'Value', windowMax);
    
    set(handles.gui.editWindowWidth, 'String', num2str(windowMin));
    set(handles.gui.editWindowLevel, 'String', num2str(windowMax))
end

function flipImageOrMask(hObject, eventdata, imageOrMask)
    handles = guidata(hObject);
    
    dim.z = 3;
    dim.y = 2;
    dim.x = 1;    
    
    options = get(handles.gui.popFlipImage, 'String');
        
    currentPosition = getSlicePosition(get(handles.gui.textSliceNumber,...
        'String'), NaN);
    
    switch imageOrMask
        case 'image'            
            % Get dimension to flip.
            dimension = getfield(dim,...
                options{get(handles.gui.popFlipImage, 'Value')});            
            handles.data.imageCoreInfo.matrix = flip(...
                handles.data.imageCoreInfo.matrix, dimension);   
            
           aspect = calculateDAspect(handles.gui.transversalOption,...
            handles.gui.sagittalOption, handles.data.imageCoreInfo.metadata{1},...
            handles.data.imageCoreInfo.metadata{2});
            
            imageSlice = squeeze(handles.data.imageCoreInfo.matrix(:, :,...
                currentPosition, :));
            
            showImageSlice(handles.gui.imageAxes,...
                imageSlice, handles.data.Rmin, handles.data.Rmax,...
                aspect);               
        otherwise  
            % Get dimension to flip.
            dimension = getfield(dim,...
                options{get(handles.gui.popFlipMask, 'Value')});
            handles.data.imageCoreInfo.masks = flip(...
                handles.data.imageCoreInfo.masks, dimension);            
    end    
    
    if get(handles.gui.showMaskCheck, 'Value')
        createMaskOverlay(handles,...
            handles.data.imageCoreInfo.masks(:, :, currentPosition),...
            aspect)
    end
        
    guidata(hObject, handles)
end

function moveSlider(hObject, ~)
    %TODO: Check mask overlay movement with slider
    handles = guidata(hObject);
    imageMatrix = handles.data.imageCoreInfo.matrix;
    nSlices = size(imageMatrix, 3);
    
    currentSlicePosition = round(get(handles.gui.slider, 'Value'));
    
    aspect = calculateDAspect(handles.gui.transversalOption,...
        handles.gui.sagittalOption, handles.data.imageCoreInfo.metadata{1},...
        handles.data.imageCoreInfo.metadata{2});
    
    imageSlice = squeeze(handles.data.imageCoreInfo.matrix(:, :,...
                currentSlicePosition, :));
    
    showImageSlice(handles.gui.imageAxes, imageSlice,...
       handles.data.Rmin, handles.data.Rmax, aspect);   
    
    % TODO: Check if mask exists
    % Check show mask state
    showMaskCheckState = get(handles.gui.showMaskCheck, 'Value');
    if showMaskCheckState
        createMaskOverlay(handles,...
            handles.data.imageCoreInfo.masks(:, :, currentSlicePosition),...
            aspect)
    end
    
    updateSliceNumberText(handles.gui.textSliceNumber,...
        currentSlicePosition, nSlices)
    
    %Refresh Slice Location information.
    updateSliceLocationText(handles.gui.textSliceLocation,...
        handles.data.imageCoreInfo.metadata, currentSlicePosition,...
        handles.data.orientation)
end

function openImage(hObject, ~)
% Import Images
handles = guidata(hObject);
if isfield(handles.data, 'lastVisitedFolder')
    rootPath = uigetdir(handles.data.lastVisitedFolder,...
        'Select a folder with Dicom images');
else
    rootPath = uigetdir('.', 'Select a folder with Dicom images');
end

if rootPath    
    try
        displayStatus(handles.gui.statusText, handles.gui.statusLight,...
            'Importing Dicoms...')
        handles.data.lastVisitedFolder = rootPath;
        handles.data.imageCoreInfo = importDicoms(rootPath);
        
        % Check if any image was found
        if ~isempty(handles.data.imageCoreInfo)            
            
           
            handles = prepareImageInformation(handles);  
            
            % Start Image State
            handles = startImageState(handles);
            
            % Start Screen Objects
            handles = startImageScreen(handles);
            
            % Get Tranversal, Sagittal and Coronal Orientation
            [matrixSagittal, matrixCoronal] = getOrientations(...,
                handles.data.imageCoreInfo.matrix);
            
            handles.data.imageCoreInfo.matrixTransversal = handles.data.imageCoreInfo.matrix;
            handles.data.imageCoreInfo.matrixSagittal = matrixSagittal;
            handles.data.imageCoreInfo.matrixCoronal = matrixCoronal;
            
            % Save imported data
            guidata(hObject, handles)            
        end
    catch errorObj
        errordlg(errorObj.message, 'Import error')
    end
    
    % Set status to ready
    displayStatus(handles.gui.statusText, handles.gui.statusLight)
    
    % Disable Mask widgets
    manipulateMaskWidgets(handles, 'Off')
end
end

function openMatFile(hObject, ~)
    handles = guidata(hObject);
    if isfield(handles.data, 'lastVisitedFolder')
        [fileName, pathName] = uigetfile('*.mat',...
            'Select a mat file containg image information',...
            handles.data.lastVisitedFolder);
    else
        [fileName, pathName] = uigetfile('*.mat',...
            'Select a mat file containg image information');
    end
    
    if ~isempty(fileName)
        try
            displayStatus(handles.gui.statusText, handles.gui.statusLight,...
                'Importing mat file...')            
            
            rootPath = [pathName fileName];
            handles.data.lastVisitedFolder = rootPath;
            
            matFile = load(rootPath);
            
            handles.data.imageCoreInfo.matrix = matFile.allResults.structure.uncalibratedLung;
            handles.data.imageCoreInfo.fileNames = {};
            handles.data.imageCoreInfo.metadata = matFile.allResults.structure.metadata;
            handles.data.imageCoreInfo.sortedIndexes = {};
            
            handles.data.imageCoreInfo.masks = matFile.allResults.structure.lungMask;
            
            % Get Tranversal, Sagittal and Coronal Orientation
            [masksSagittal, masksCoronal] = getOrientations(...,
                handles.data.imageCoreInfo.masks);
            
            handles.data.imageCoreInfo.masksTransversal = handles.data.imageCoreInfo.masks;
            handles.data.imageCoreInfo.masksSagittal = masksSagittal;
            handles.data.imageCoreInfo.masksCoronal = masksCoronal;
            
            handles = prepareImageInformation(handles);           
            
            % Start Image State
            handles = startImageState(handles);
            
            % Start Screen Objects
            handles = startImageScreen(handles);
            
            % Save imported mask
            guidata(hObject, handles)
        catch errorObj
            errordlg(errorObj.message, 'Import error');
        end
    end
    % Set status to ready!
    displayStatus(handles.gui.statusText, handles.gui.statusLight)
end

function handles = prepareImageInformation(handles)
    imageSize = size(handles.data.imageCoreInfo.matrix);
    handles.data.imageCoreInfo.sizeTransversal = imageSize(3);
    handles.data.imageCoreInfo.sizeSagittal = imageSize(2);
    handles.data.imageCoreInfo.sizeCoronal = imageSize(1);
    handles.data.imageCoreInfo.nSlices = imageSize(3);
    
    % Calculate Voxel Volume
    handles.data.voxelVolume = calculateVoxelVolume(...
        handles.data.imageCoreInfo.metadata{1},...
        handles.data.imageCoreInfo.metadata{2});
    
    % Get Sagittal and Coronal Orientation
    % Get Tranversal, Sagittal and Coronal Orientation
    [matrixSagittal, matrixCoronal] = getOrientations(...,
        handles.data.imageCoreInfo.matrix);
    
    handles.data.imageCoreInfo.matrixTransversal = handles.data.imageCoreInfo.matrix;
    handles.data.imageCoreInfo.matrixSagittal = matrixSagittal;
    handles.data.imageCoreInfo.matrixCoronal = matrixCoronal;
end


function openMask(hObject, ~)
    handles = guidata(hObject);
    if isfield(handles.data, 'lastVisitedFolder')
        [fileName, pathName] = uigetfile('*.hdr;*.nrrd',...
            'Select the file containing the masks',...
            handles.data.lastVisitedFolder);
    else
        [fileName, pathName] = uigetfile('*.hdr;*.nrrd',...
            'Select the file containing the masks');
    end
    
    if ~isempty(fileName)
        try
            displayStatus(handles.gui.statusText, handles.gui.statusLight,...
                'Importing masks...')
            
            rootPath = [pathName fileName];
            handles.data.imageCoreInfo.masks = importMasks(rootPath);
            handles.data.lastVisitedFolder = rootPath;
            
            % Enable mask widgets
            manipulateMaskWidgets(handles, 'On')
            
            % Get Tranversal, Sagittal and Coronal Orientation
            [masksSagittal, masksCoronal] = getOrientations(...,
                handles.data.imageCoreInfo.masks);
            
            handles.data.imageCoreInfo.masksTransversal = handles.data.imageCoreInfo.masks;
            handles.data.imageCoreInfo.masksSagittal = masksSagittal;
            handles.data.imageCoreInfo.masksCoronal = masksCoronal;            
            
            % Mask Settings
            handles.data.imageCoreInfo.maskSettings.rgb = [0, 1, 0];
            handles.data.imageCoreInfo.maskSettings.opacity = 0.5;
            
            % Save imported mask
            guidata(hObject, handles)           
            
        catch errorObj
            errordlg(errorObj.message, 'Import error');
        end
    end
    % Set status to ready!
    displayStatus(handles.gui.statusText, handles.gui.statusLight)
end


function mouseMove(hObject, ~)
    handles = guidata(hObject);
    if ~isempty(handles) && isfield(handles.data, 'imageCoreInfo')
        imageAxes = handles.gui.imageAxes;
        refreshPixelPositionInfo(handles, imageAxes);
    end
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                             UTILS                                
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function maskOverlayWrapper(handles)
    aspect = calculateDAspect(handles.gui.transversalOption,...
        handles.gui.sagittalOption, handles.data.imageCoreInfo.metadata{1},...
        handles.data.imageCoreInfo.metadata{2});

    slicePosition = extractSlicePosition(...
        get(handles.gui.textSliceNumber, 'String'));
    createMaskOverlay(handles, handles.data.imageCoreInfo.masks(:, :,...
        slicePosition), aspect)
end

function voxelVolume = calculateVoxelVolume(metadata, metadata2)
voxelVolume = NaN;
if isfield(metadata,'SpacingBetweenSlices')
    if isfield(metadata,'SliceThickness')
        if abs(metadata.SpacingBetweenSlices) < metadata.SliceThickness
            voxelVolume =(metadata.PixelSpacing(1) ^ 2 *...
                metadata.SliceThickness * 0.001) *...
                (abs(metadata.SpacingBetweenSlices) / metadata.SliceThickness);
        else
            voxelVolume = (metadata.PixelSpacing(1) ^ 2 *...
                metadata.SliceThickness * 0.001);
        end
    else
        voxelVolume = (metadata.PixelSpacing(1) ^ 2 *...
            metadata.SliceThickness * 0.001);
    end
else
    
    if isfield(metadata,'SliceThickness')==1;
        thick=abs(metadata.SliceThickness);
    elseif isfield(metadata,'SpacingBetweenSlices');
        thick=abs(metadata.SpacingBetweenSlices);
    else
        thick=abs(metadata.PixelDimensions(3));
    end
    
    if isfield(metadata, 'SliceLocation')
        SpacingBetweenSlices = abs(metadata2.SliceLocation -...
            metadata.SliceLocation);
    end
    
    if isfield(metadata, 'SliceThickness') && exist('SpacingBetweenSlices')
        SliceThickness = metadata.SliceThickness;
        voxelVolume = (metadata.PixelSpacing(1) ^ 2 * thick * 0.001) *...
            (SpacingBetweenSlices / SliceThickness);
    end
end
end

function refreshWindowWidthLevel(handles, windowWidth, windowLevel)
    if (windowWidth < 1)
        windowWidth = 1;
    end
   
    [Rmin, Rmax] = WL2R(windowWidth,windowLevel);
    
    updateWindowWidthLevel(handles.gui.textWindowWL, windowWidth,...
        windowLevel)
    
    set(handles.gui.sliderWindowWidth, 'Value', windowWidth);
    set(handles.gui.sliderWindowLevel, 'Value', windowLevel);
    
    set(handles.gui.imageAxes, 'Clim', [Rmin, Rmax]);
    
     % Update Window Width Text
    set(handles.gui.editWindowWidth, 'String', num2str(round(windowWidth)));
    set(handles.gui.editWindowLevel, 'String', num2str(round(windowLevel)));
end

%TODO Force to show chosen Orientation View
function aspect = calculateDAspect(transversal, sagittal, metadata_1, metadata_2)
    orientation = getOrientationName(transversal, sagittal);
    
    if isfield(metadata_1, 'SliceLocation') &&...
            isfield(metadata_2, 'SliceLocation') && ...
            ~strcmp(orientation, 'transversal')
        diffSliceLoc = abs(metadata_1.SliceLocation -...
            metadata_2.SliceLocation);
        
        pixelSpacing = metadata_1.PixelSpacing(1);
        aspect = [diffSliceLoc / pixelSpacing, 1, 1];
    else
         aspect = [1, 1, 1];
    end
end

function orientation = getOrientationName(transversal, sagittal)
    transversalValue = get(transversal, 'Value');
    sagittalValue = get(sagittal, 'Value');
    
    if transversalValue
        orientation = 'transversal';
    elseif sagittalValue
        orientation = 'sagittal';
    else
        orientation = 'coronal';
    end
end

function [imageSagittal, imageCoronal] = getOrientations(imageMatrix)
    imageSagittal = flip(permute(imageMatrix, [3 1 2 4]),1);
    imageCoronal = flip(permute(imageMatrix, [3 2 1 4]), 1);
end

function handles = startImageState(handles)
    if ~isfield(handles.data, 'orientation')
        handles.data.orientation = 'transversal';
    end
end

function handles = startImageScreen(handles)
%Calculate Window Coefficients
    [Rmin, Rmax, Win, LevV] = windowCoeffAdj...
       (handles.data.imageCoreInfo.matrix);
    handles.data.Rmin = Rmin;
    handles.data.Rmax = Rmax;
    handles.data.Win = Win;
    handles.data.LevV = LevV;

    % Show window width and level
    updateWindowWidthLevel(handles.gui.textWindowWL, Win, LevV)
    % Update Window Width Text
    set(handles.gui.editWindowWidth, 'String',...
        num2str(round(Rmin)));
    % Update Window Level Text
    set(handles.gui.editWindowLevel, 'String',...
        num2str(round(Rmax)));

    %Prepare Window max and min sliders
    startWindowWidthLevelSliders(handles,...
        handles.data.imageCoreInfo.matrix, Win, LevV)

    % Enable controls
    set(handles.gui.importMaskButton, 'Enable', 'On')

    % Enable image related widgets
    set(handles.gui.buttonFlipImage, 'Enable', 'On');
    set(handles.gui.textWindowWL, 'Visible', 'On');

    firstPosition = startSlider(handles.gui.slider,...
        handles.data.imageCoreInfo.nSlices);
    
    %TODO: Create one function for these 3
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    aspect = calculateDAspect(handles.gui.transversalOption,...
        handles.gui.sagittalOption, handles.data.imageCoreInfo.metadata{1},...
        handles.data.imageCoreInfo.metadata{2});
    
    imageSlice = squeeze(handles.data.imageCoreInfo.matrix(:, :,...
                firstPosition, :));
    
     %Show first Slice
    showImageSlice(handles.gui.imageAxes,...
        imageSlice, handles.data.Rmin, handles.data.Rmax,...
        aspect);        
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    
    
    % Show metadata on the screen
    startScreenMetadata(handles,...
        handles.data.imageCoreInfo.metadata{1},...
        firstPosition, size(handles.data.imageCoreInfo.matrix, 3))

    % Enable mask widgets
    manipulateMaskWidgets(handles, 'On')
end


function manipulateMaskWidgets(handles, onOff)
    % Enable show mask checkbox
    set(handles.gui.showMaskCheck, 'Enable', onOff)

    % Enable mask related widgets
    set(handles.gui.buttonFlipMask, 'Enable', onOff);
    
    % Enale mask settigns
    set(handles.gui.buttonMaskSettings, 'Enable', onOff);
end

function updateWindowWidthLevel(textObject, Win, LevV)
    set(textObject, 'String', sprintf('WW / WL: %d / %d',...
        int16(Win), int16(LevV)))
end

function firstPosition = startSlider(sliderObject, nSlices)
    firstPosition = round(nSlices / 2);
    set(sliderObject, 'Visible', 'On',...
        'Min', 1,...
        'Max', nSlices,...
        'SliderStep', [1  / (nSlices - 1) 10 / (nSlices - 1)],...
        'Value', firstPosition);
end

function showImageSlice(axisObject, imageSlice, Rmin, Rmax, aspect)
    axesChildren = get(axisObject, 'children');
    if ~isempty(axesChildren)
        set(axesChildren, 'cdata', imageSlice);  
    else
        axes(axisObject)
        imshow(imageSlice, [Rmin, Rmax])
    end
    colormap(gray)
    set(axisObject, 'XtickLabel', [])
    set(axisObject, 'YtickLabel', [])
    axis('tight')
    daspect(aspect);    
end

function updateSliceNumberText(textObject, sliceNumber, nSlices)
    set(textObject, 'String', sprintf('%d / %d', sliceNumber, nSlices));
end

function updateSliceLocationText(textObject, metadata,  sliceIndex, orientation)
    if strcmp(orientation, 'transversal')
        if sliceIndex > 0
          metadata = metadata{sliceIndex};
        end
        if isfield(metadata, 'SliceLocation')
             set(textObject, 'String',...
             sprintf('Slice Location: %.2f', metadata.SliceLocation));
        end
    end
end

function startScreenMetadata(handles, metadata, firstPosition, nSlices)
    %Show Patient Name
    updatePatientName(handles.gui.textPatientName, metadata)
    
    % Display Voxel Volume
    if isfield(handles.data, 'voxelVolume')
        if isnan(handles.data.voxelVolume)
            set(handles.gui.textVoxelVolume, 'String','Not Available')
        else
            set(handles.gui.textVoxelVolume, 'String',...
                sprintf('%.4fL', handles.data.voxelVolume))
        end
    end
    
    %
    if isfield(metadata, 'PatientAge')
        set(handles.gui.textAge, 'String',...
            metadata.PatientAge)
    end
    
    %
    updateStudyDescription(handles.gui.textStudyDescription, metadata);
    
    %
    updateSeriesDescription(handles.gui.textSeriesDescription, metadata);
 
    %
    if isfield(metadata, 'StudyDate')
        set(handles.gui.textStudyDate, 'String',...
            formatStudyDate(metadata.StudyDate))        
        
    end    
    
    % Show Slice Number
    updateSliceNumberText(handles.gui.textSliceNumber, firstPosition,...
        size(handles.data.imageCoreInfo.matrix, 3))
        
    updateSliceLocationText(handles.gui.textSliceLocation,...
        metadata, -1, handles.data.orientation)
        
    % Show Image Dimensions
    set(handles.gui.textImageDimensions, 'String',...
        sprintf('%d x %d x %d', metadata.Rows,...
        metadata.Columns, nSlices));
    
    if isfield(metadata, 'SpacingBetweenSlices')
        set(handles.gui.textSpacingBetweenSlices, 'String',...
            sprintf('%.2fmm', metadata.SpacingBetweenSlices));
    elseif isfield(metadata, 'SliceLocation')
        spacingBetweenSlices = calculateSpacingBtwSlices(...
            handles.data.imageCoreInfo.metadata);        
        set(handles.gui.textSpacingBetweenSlices, 'String',...
            sprintf('%.2fmm', spacingBetweenSlices));
    end
    
    set(handles.gui.textSliceThickness, 'String',...
        sprintf('%.2fmm', metadata.SliceThickness));
    
end

function updatePatientName(textObject, metadata)
    if isfield(metadata, 'PatientName')
        if isfield(metadata.PatientName, 'FamilyName')
            patientName = metadata.PatientName.FamilyName;
        else
            patientName = metadata.PatientName;
        end
        
        if length(patientName) > 22
            patientName = [patientName(1:22), '...'];
        end
        set(textObject, 'String', patientName);
    end
end

function updateStudyDescription(textObject, metadata)
    if isfield(metadata, 'StudyDescription')
        
        studyDescription = metadata.StudyDescription;
        
        if length(studyDescription) > 22
            studyDescription = [studyDescription(1:22), '...'];
        end
        set(textObject, 'String', studyDescription);
    end   
end

function updateSeriesDescription(textObject, metadata)
    if isfield(metadata, 'SeriesDescription')
        
        seriesDescription = metadata.SeriesDescription;
        
        if length(seriesDescription) > 22
            seriesDescription = [seriesDescription(1:22), '...'];
        end
        set(textObject, 'String', seriesDescription);
    end   
end

function refreshPixelPositionInfo(handles, mainAxes)

if isfield(handles, 'data')
    C = get(mainAxes,'currentpoint');

    xlim = get(mainAxes,'xlim');
    ylim = get(mainAxes,'ylim');

    row = round(C(1));
    col = round(C(1, 2));

    %Check if pointer is inside Navigation Axes.
    outX = ~any(diff([xlim(1) C(1,1) xlim(2)])<0);
    outY = ~any(diff([ylim(1) C(1,2) ylim(2)])<0);
    if outX && outY && row && col
        %Get the current Slice
        currentSlicePositionString = get(handles.gui.textSliceNumber,...
            'String');
        tempSlicePosition = regexp(currentSlicePositionString, '/',...
            'split');
        slicePosition = str2double(tempSlicePosition(1));

        currentSlice = handles.data.imageCoreInfo.matrix(:, :,...
            slicePosition);

        pixelValue = currentSlice(col, row);

        set(handles.gui.textPixelValue, 'String',...
            sprintf('Pixel: (%d, %d): %d', col, row, double(pixelValue)))
    else
        set(handles.gui.textPixelValue, 'String',...
            sprintf(''))
    end

end
end

function newSlicePosition = getSlicePosition(slicePositionString, direction)
     slicePosition = extractSlicePosition(slicePositionString);
    
    if nargin == 1
        direction = NaN;
    end

    if isnan(direction)
        newSlicePosition = slicePosition;
    elseif direction >= 0
        newSlicePosition = slicePosition + 1;
    else
        newSlicePosition = slicePosition - 1;
    end
end

function slicePosition = extractSlicePosition(slicePosStr)
    tempSlicePosition = regexp(slicePosStr, '/', 'split');
    slicePosition = str2double(tempSlicePosition(1));
end

function refreshSlicePosition(hObject, eventdata)

slicePositionPlaceHolder = '%d / %d';

handles = guidata(hObject);

if ~isempty(handles.data)

    nSlices = handles.data.imageCoreInfo.nSlices;

    currentSlicePosition = get(handles.gui.textSliceNumber, 'String');

    %Get the new slice position based on the displayed values using regexp
    if isprop(eventdata, 'VerticalScrollCount')
        newSlicePosition = getSlicePosition(currentSlicePosition,...
            eventdata.VerticalScrollCount);
    else
        newSlicePosition = getSlicePosition(currentSlicePosition);
    end
       
    %Make sure that the slice number return to 1 if it is bigger than the
    %number of slices
    newSlicePosition = mod(newSlicePosition, nSlices);

    %Make sure that the slice number return to nSlices if it is smaller than the
    %number of slices
    if ~newSlicePosition && eventdata.VerticalScrollCount < 0
        newSlicePosition = nSlices;
    elseif ~newSlicePosition && eventdata.VerticalScrollCount >= 0 %%% -- INFO -- matlab has some hard time with the scroll of my laptop, in this case VerticalScrollCount == 0, it get an error latter in this function and this is error realy I need to restart matlab. I changed > to >=
        newSlicePosition = 1;
    end

    %Refresh slice position information.
    set(handles.gui.textSliceNumber, 'String',...
        sprintf(slicePositionPlaceHolder, newSlicePosition, nSlices));
  
    aspect = calculateDAspect(handles.gui.transversalOption,...
        handles.gui.sagittalOption, handles.data.imageCoreInfo.metadata{1},...
        handles.data.imageCoreInfo.metadata{2});
    
    imageSlice = squeeze(handles.data.imageCoreInfo.matrix(:, :,...
        newSlicePosition, :));
    
    showImageSlice(handles.gui.imageAxes, imageSlice,...
       handles.data.Rmin, handles.data.Rmax, aspect);    

    %Refresh pixel value information.
    refreshPixelPositionInfo(handles, handles.gui.imageAxes)
    
    %Refresh Slice Location information.
   updateSliceLocationText(handles.gui.textSliceLocation,...
        handles.data.imageCoreInfo.metadata, newSlicePosition,...
        handles.data.orientation);
    
    %Refresh slider value
    set(handles.gui.slider, 'Value', newSlicePosition);

    % Check show mask state
    showMaskCheckState = get(handles.gui.showMaskCheck, 'Value');
    if showMaskCheckState
        maskOverlayWrapper(handles)
    end
    
    guidata(hObject, handles)
end
end

function showMask(hObject, eventdata)
    handles = guidata(hObject);
    set(handles.gui.imageAxes, 'NextPlot', 'Replace')
    showMaskCheckState = get(handles.gui.showMaskCheck, 'Value');
    
    if showMaskCheckState
        slicePositionString = get(handles.gui.textSliceNumber, 'String');
        currentSlicePosition = getSlicePosition(slicePositionString);
        mask = handles.data.imageCoreInfo.masks(:, :, currentSlicePosition);
        
        aspect = calculateDAspect(handles.gui.transversalOption,...
            handles.gui.sagittalOption, handles.data.imageCoreInfo.metadata{1},...
            handles.data.imageCoreInfo.metadata{2});
        
        createMaskOverlay(handles, mask, aspect)
    else
        % Delete maskOverlay object to make navigation faster
        delete(findobj(handles.gui.imageAxes, 'Tag', 'maskOverlay'))
        refreshSlicePosition(hObject, eventdata)
    end   
end

 function createMaskOverlay(handles, mask, aspect)
    nRows = size(mask, 1);
    nCols = size(mask, 2);
    mask = mask >= 1;
 
    
    overlayColor = handles.data.imageCoreInfo.maskSettings.rgb;
    defaultOpacity = handles.data.imageCoreInfo.maskSettings.opacity;

%     switch overlayColor
%         case {'y','yellow'}
%             overlayColor = [1 1 0];
%         case {'m','magenta'}
%             overlayColor = [1 0 1];
%         case {'c','cyan'}
%             overlayColor = [0 1 1];
%         case {'r','red'}
%             overlayColor = [1 0 0];
%         case {'g','green'}
%             overlayColor = [0 1 0];
%         case {'b','blue'}
%             overlayColor = [0 0 1];
%         case {'w','white'}
%             overlayColor = [1 1 1];            
%         case {'k','black'}
%             overlayColor = [0 0 0];
%     end
    
    colorMask = ones(nRows, nCols, 3);
    colorMask(:, :, 1) = colorMask(:, :, 1) * overlayColor(1);
    colorMask(:, :, 2) = colorMask(:, :, 2) * overlayColor(2);
    colorMask(:, :, 3) = colorMask(:, :, 3) * overlayColor(3);
    
    delete(findobj(handles.gui.imageAxes, 'Tag', 'maskOverlay'))
    hold on
    h = imshow(colorMask);
    set(h, 'AlphaData', mask * defaultOpacity, 'tag', 'maskOverlay');   
    daspect(aspect);
    hold off
 end

 function [Rmin, Rmax, Win, LevV] = windowCoeffAdj(Img)
    Win = double(max(Img(:)) - min(Img(:)));
    %Win (Win < 1) = 1;
    LevV = double(min(Img(:)) + (Win/2));
    [Rmin, Rmax] = WL2R(Win, LevV);
 end
 
 function [Rmn, Rmx] = WL2R(W,L)
    Rmn = L - (W/2);
    Rmx = L + (W/2);
    if (Rmn >= Rmx)
        Rmx = Rmn + 1;
    end
 end

 function formattedStudyDate = formatStudyDate(studyDate)
 formattedStudyDate = [studyDate(5:6), '-',studyDate(7:8),...
     '-', studyDate(1:4)];
 end
 
 function spacingBtwSlices = calculateSpacingBtwSlices(metadata)
    spacingBtwSlices = abs(metadata{1}.SliceLocation - metadata{2}.SliceLocation);
 end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                 LOG                           
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function displayStatus(statusText, statusLight, msg)

    if nargin == 2
        set(statusText, 'String', 'Ready!')
        set(statusLight, 'Backgroundcolor', 'g');
    else        
        set(statusText, 'String', msg)
        set(statusLight, 'Backgroundcolor', 'r');
    end
    drawnow
end